sudo: false


    
language: python
python: 2.7

 
virtualenv:
   system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML_validate


install:
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - omv list -V 
    
    
    
    

