sudo: false


    
language: python
python: 2.7

 
virtualenv:
   system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML_validate


script:
    - omv all -V
    - omv list -V 
    
    
    
    

